### ISSUE TITLE
Need help simplifying this to hash lines of text file

### ISSUE THREAD

**Issue by merclyn** [Horkyze/CudaSHA256#2]
I was trying to use your code as a starting point to make a sha256 cuda hasher that takes lines from stdin (Or any text file) and hashes each line as a job (Outputing HASH and Original Line in the output separated by a space or other delimiter)

Your program is so close to doing this (You hash filesystem files), but my c++ is weak.  Can you assist me?   The way you read the files in for the –f switch, but instead of getting the file data from get_file_data, could you just hash the string?

**Comment by Horkyze** [comment]
Hi, of course you can!

Notice this line: https://github.com/Horkyze/CudaSHA256/blob/adf4de722dc2a8371da94c3323f1b979ecbbbbf0/main.cu#L194

`buff` stands for buffer and it's nothing else then a string. So you can pass in whatever you want. 
If you dont know how to read input from stdin, I suggest you google that, there are a lot of good tutorials out there.

**Comment by merclyn** [comment]
I thought I tried that earlier, ill try it again.   
In your code, if I passed in the variable line in place of buff, should I replace temp with strlen(line)?  this is what I thought I did.  Once I have it working with a string, I can easily get stdin working.  Ill give it a shot later in the day.

Again, Thanks for the help.

**Comment by merclyn** [comment]
Im real close, but still cigar.

I added these 3 lines directly above the line 194 you refer to above:
                                buff = (BYTE *)"Hello";
                                checkCudaErrors(cudaMallocManaged(&buff, (5)*sizeof(char)));
                                jobs[i] = JOB_init(buff, 5, argv[index]);
and I get this hash:
8855508aade16ec573d21e6a485dfd0a7624085c1a14b5ecdd6485de0c6839a4  file.1
but I believe the hash is incorrect, because I compare it to:
$ echo -n "Hello" | sha256sum
and I get:
185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969  -

I would expect the hash from both of those to match exactly.

BTW: If I dont cast buff to (BYTE *) then I get a compile error.  Once I have this working with a simple string, ill be able to take it from there.

**Comment by merclyn** [comment]
I have some progress.  I seem to need to better understand variable pointers in c++.

**Comment by Fyzjym** [comment]
Hello, may I ask for your help?

After I modify the code, I get an incorrect hash value.

				buff = (BYTE *)"abc";
				checkCudaErrors(cudaMallocManaged(&buff, (3)*sizeof(char)));
				jobs[i] = JOB_init(buff, 3, argv[index]);
