### ISSUE TITLE
Hello, may I ask for your help?

### ISSUE THREAD

**Issue by Fyzjym** [Horkyze/CudaSHA256#4]
Hello, may I ask for your help?

After I modify the code, I get an incorrect hash value.

			buff = (BYTE *)"abc";
			checkCudaErrors(cudaMallocManaged(&buff, (3)*sizeof(char)));
			jobs[i] = JOB_init(buff, 3, argv[index]);

**Comment by levicki** [comment]
That's because you are changing the code incorrectly.

You are not supposed to change:
```
checkCudaErrors(cudaMallocManaged(&jobs, n * sizeof(JOB *)));
```
Into:
```
checkCudaErrors(cudaMallocManaged(&buff, (3)*sizeof(char)));
```
Try reading the code again to understand what that line actually does.

**Comment by Fyzjym** [comment]
Thanks you, sir. I will check it now. :D
