### ISSUE TITLE
Cannot handle files > 4GB

### ISSUE THREAD

**Issue by levicki** [Horkyze/CudaSHA256#5]
As the title says, the file API used does not allow working with files larger than 4 GB. With cards that have up to 24 GB of VRAM like 3090 RTX and with fast SSDs that would probably be a better use case than doing sha256 on a GPU for a bunch of small files where just the latency of the request is going to hide all the benefits of fast calculation.

Consider changing file API to something that can handle 64-bit file sizes, and consider using ptrdiff_t instead of char for pointer arithmetic.

**Comment by Horkyze** [comment]
Hello, I no longer develop this utility it was a school project. Feel free to submit PR or fork it and continue on your own.

**Comment by levicki** [comment]
Sorry, wasn't aware of that. Thanks for the code.
